# The AAR is generated by gomobile and exposes Java proxy classes that are
# looked up through JNI. Keep the bridge and the application callbacks in a
# minified release build.
-keep class usqueandroid.** { *; }
-keep class go.** { *; }
-keep class com.abobo.usquevpn.** { *; }
-keepclassmembers class * implements usqueandroid.PacketFlow { *; }
-keepclassmembers class * implements usqueandroid.VpnStateCallback { *; }
